# Generated by Django 2.2.9 on 2019-12-29 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shakes', to='shake.ViettelUser'),
        ),
    ]
