# Generated by Django 2.2.9 on 2019-12-29 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shake', '0002_auto_20191229_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='shake',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
