# Generated by Django 2.2.9 on 2020-01-01 07:43

from django.db import migrations


def set_phone_prefix_zero(apps, schema_editor):
    ViettelUser = apps.get_model('shake', 'ViettelUser')
    for user in ViettelUser.objects.all():
        phone = str(user.phone)
        if phone[0] != '0':
            user.phone = '0' + phone
            user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('shake', '0004_auto_20191231_0959'),
    ]

    operations = [
        migrations.RunPython(set_phone_prefix_zero),
    ]
