# Generated by Django 2.2.9 on 2020-01-01 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shake', '0005_auto_20200101_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='vietteluser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
